Bill.create!(name: 'One Thousand', amount: 1000)
Bill.create!(name: 'Five Hundred', amount: 500)
Bill.create!(name: 'Two Hundred', amount: 200)
Bill.create!(name: 'One Hundred', amount: 100)
Bill.create!(name: 'Fifty', amount: 50)
Bill.create!(name: 'Twenty', amount: 20)

Bill.create!(name: 'Ten', amount: 10)
Bill.create!(name: 'Five', amount: 5)
Bill.create!(name: 'One', amount: 1)
Bill.create!(name: 'Twenty Five Cents', amount: 0.25)
